SET IDENTITY_INSERT COMUM.TB_PRODUTO  ON
INSERT INTO COMUM.TB_PRODUTO (PR_ID,PR_NOME,PR_DESCRICAO,PR_TITULO_IMG,PR_IMG_PRINCIPAL,PR_CSS_DEFAULT,PL_ID) VALUES (401,'patrimonio-intangivel','Módulo de Patrimônio Intangível.','','','default',1);
SET IDENTITY_INSERT COMUM.TB_PRODUTO  OFF

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginTipo','INTERNO',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAreaInterno','Área do Servidor',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginChaveAcessoInterno','Usuário do Compras',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginFacebookInterno','false',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginEsqueceuSenhaInterno','true',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAutoCadastroInterno','true',401);

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAreaExterno','Área do Fornecedor',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginChaveAcessoExterno','CPF ou Email',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginFacebookExterno','false',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginEsqueceuSenhaExterno','false',401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PR_ID) VALUES ('loginAutoCadastroExterno','false',401);

INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logo', 'repo1:patrimoniointangivel/logo.svg', 'ARQUIVO', 401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoEmail', 'repo1:patrimoniointangivel/logoEmail.png', 'ARQUIVO', 401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoMenu', 'repo1:patrimoniointangivel/logoMenu.svg', 'ARQUIVO', 401);
INSERT INTO COMUM.TB_PRODUTO_ATRIBUTO ( PA_ATRIBUTO, PA_VALOR, PA_TIPO, PR_ID) VALUES ('logoMenuRetraido', 'repo1:patrimoniointangivel/logoMenuRetraido.svg', 'ARQUIVO', 401);